### ISSUE TITLE
nicht IPS 4.2 kompatibel

### ISSUE THREAD

**Issue by Nall-chan** [nik78476/SymconPegelstand#1]
Timer Funktionen sind in IPSModul Klasse vorhanden, bitte nicht mehr überschreiben.
Destroy für Timer wird nicht benötigt.
Unterordnern welche keine Module enthalten sind nicht mehr erlaubt (Ausnahme docs, libs und Images).
Für Debug Ausgaben gibt es SendDebug.
Debug Property somit auch unnötig.

**Comment by nik78476** [comment]
Danke für die Tips, werde sie einarbeiten

**Comment by nik78476** [comment]
fixed

**Comment by Nall-chan** [comment]
Sicher dass du die Daten alle 14,4 Sekunden abrufen willst ;) 
Nicht 14400 *1000 ?
Das *1000 fehlt auch beim SetTimerInterval

**Comment by Nall-chan** [comment]
Und Screenshots solltest du auf imgs ändern.
https://www.symcon.de/service/dokumentation/entwicklerbereich/sdk-tools/sdk-php/struktur/
